name: Validate Token List (Main Branch)

on:
  push:
    branches: [ main ]
    paths:
      - 'src/tokens/**'
      - 'src/assets/**'
      - 'schemas/**'
  
  schedule:
    # Run validation daily at 12:00 UTC
    - cron: '0 12 * * *'
    
  workflow_dispatch:
    # Allow manual triggering

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Run full validation
      run: pnpm run validate
      
    - name: Run linting and type checking
      run: |
        pnpm run lint
        pnpm run check
        
    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const title = `🚨 Token List Validation Failed on Main Branch`;
          const body = `The automated validation of the token list has failed on the main branch.
          
          **Workflow Run:** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          **Commit:** ${{ github.sha }}
          **Triggered by:** ${{ github.event_name }}
          
          Please investigate and fix the validation errors immediately to maintain the integrity of the token list.
          
          This issue was automatically created by the validation workflow.`;
          
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: ['bug', 'validation-failure', 'priority-high']
          });